# -*- coding: utf-8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import os


def even_fib_num(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b


def main():
    print(sum(n for n in even_fib_num(4e6) if not (n & 1)))
    print('Tests Passed!')

if __name__ == '__main__':
    main()

os.system("pause")
